# Generated by Django 5.0 on 2023-12-12 14:16

import django.core.validators
import form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student_no', models.IntegerField(unique=True)),
                ('branch', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('year', models.CharField( max_length=5)),
                ('residence', models.CharField( max_length=15)),
            ],
        ),
    ]
