# Generated by Django 4.1.13 on 2024-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student_no', models.IntegerField(unique=True)),
                ('branch', models.CharField(max_length=10)),
                ('section', models.IntegerField()),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('phone_number', models.IntegerField()),
                ('hackerRank_username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Registered User',
            },
        ),
    ]
