# Generated by Django 5.0 on 2023-12-20 16:26

import django.core.validators
import form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.CharField( max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.CharField( max_length=10),
        ),
    ]
