# Generated by Django 4.1.13 on 2024-09-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
