# Generated by Django 5.0 on 2023-12-20 16:26

import django.core.validators
import form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2100000), django.core.validators.MaxValueValidator(22999999), form.models.validate_Student_digits]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.CharField(choices=[('2', '2'), ('3', '3')], max_length=10),
        ),
    ]
