# Generated by Django 4.1.13 on 2024-09-13 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_registration_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='residence',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
