# Generated by Django 5.0 on 2024-08-02 03:55

import django.core.validators
import form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_registration_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': 'Registered User'},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='year',
        ),
        migrations.AddField(
            model_name='registration',
            name='hackerRank_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20), form.models.validate_Section_digits]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2200000), django.core.validators.MaxValueValidator(23999999), form.models.validate_Student_digits]),
        ),
    ]
